### PR TITLE
LPS-96865 Allow scrolling on the preview but block all clicks to avoid navigation within the iframe

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74797. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
