### PR TITLE
LPS-94469 Empty experiences

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by andresfulla** [comment]
Just so you know, this is on top of https://github.com/brianchandotcom/liferay-portal/pull/73430

**Comment by p2kmgcl** [comment]
Just started reviewing :)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73453.

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73456. [See changes here.](https://github.com/p2kmgcl/liferay-portal/compare/9fe5f5f45018~1...9fe5f5f45018)

**Pull request closed without merging**
