### PR TITLE
LPS-77297 Add missing initial state for aria-expanded attribute

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by p2kmgcl** [comment]
https://github.com/ealonso/liferay-portal/pull/1404
:D

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/sandrodw3/liferay-portal/pull/48. [See changes here.](https://github.com/p2kmgcl/liferay-portal/compare/7b00cdefc604~8...7b00cdefc604)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/326. [See changes here.](https://github.com/p2kmgcl/liferay-portal/compare/3e055a4aef5b~7...3e055a4aef5b)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/sandrodw3/liferay-portal/pull/49.

**Pull request closed without merging**
