### PR TITLE
LPS-92806 Layout by experience reviewed

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by andresfulla** [comment]
Just rebased to solve those `setIn` conflicts. Also removed the `Bringing tests back to normal` as they cannot be run normally with latest changes.

**Comment by p2kmgcl** [comment]
Just started reviewing :)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71445. [See changes here.](https://github.com/p2kmgcl/liferay-portal/compare/5e61ede8bcb2~2...5e61ede8bcb2)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71446. [See changes here.](https://github.com/p2kmgcl/liferay-portal/compare/b88ef8098f31~3...b88ef8098f31)

**Pull request closed without merging**
