### PR TITLE
[TECHNICAL-SUPPORT] LPS-92958

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @brianikim 

Notes from Josh:

> https://issues.liferay.com/browse/LPS-92958
> 
> The issue here is that the restore drop-down notification is not using Clay.
> 
> The fix is to apply the cssClass used by Clay that allows Clay-style modifications.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Let me know if you have any questions regarding the PR @p2kmgcl .

Sincerely,
Brian Kim

**Comment by p2kmgcl** [comment]
Just started reviewing :)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70796.

**Pull request closed without merging**
