### PR TITLE
LPS-106345 | Update Experiences priorities

### PR DESCRIPTION
**Pull request by andresfulla**
@p2kmgcl @dgarciasarai @victorg1991 @sandrodw3 @ealonso

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
I'm gonna check this today :loveparrot:

**Pull request closed without merging**
