### PR TITLE
LPS-98842 Fix typo in UserIcon.es.js

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-98842](https://issues.liferay.com/browse/LPS-98842).

Hey @p2kmgcl, not sure who this should go to so I just looked at the file authors :)

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76270. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
D: what a mistake

Thanks @drewbrokke!

**Comment by drewbrokke** [comment]
Anytime! It can happen to anyone :)

**Pull request closed without merging**
