### PR TITLE
LPS-84373 node-event-simulate dependency added in AUI script to fix error

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62257. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
