### PR TITLE
LPS-112037 Rename macro

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl and @sandrodw3 
Buttons
Is this expected?

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl  Could you check your code about this failure https://testray.liferay.com/reports/production/logs/test-1-7/1594165923927/test-portal-acceptance-pullrequest(master)/5805/functional-tomcat90-mysql57-jdk8/1/0/LocalFile.ContentPageConverter_ViewAndEditConversionDraftPage/index.html.gz
Can not reproduce on manually. Only run case. You can also run the following one Fragments#ConfigureBasicComponentButton

**Comment by p2kmgcl** [comment]
> Hi @p2kmgcl and @sandrodw3
> Buttons
> Is this expected?

no it isn't, fixed! :D

**Pull request closed without merging**
