### PR TITLE
LPS-107695 Add image alignment options to the rich text editor toolbar

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci::man_shrugging:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by jpince** [comment]
@yichenroy I think we should remove ci emoji support... it looks like the comment ci::man_shrugging: resulted in `ci:test:default` :joy:

**Comment by yichenroy** [comment]
@jpince that is strange, let me test it out. 
There's filters to check for `ci:test` so `ci:man_shrugging` shouldn't have triggered anything.

**Comment by brianchandotcom** [comment]
@pavel-savinov @p2kmgcl I merged this for you guys because @jpince told me to

**Comment by jpince** [comment]
ci:close

**Comment by yichenroy** [comment]
ci:close
Previous command didn't work?

**Comment by yichenroy** [comment]
@p2kmgcl @pavel-savinov please reference this [article](https://grow.liferay.com/people/Pull+Request+Tester+for+Liferay+Developers) to add `liferay-continuous-integration` as a collaborator for `liferay-portal` repository if it isn't already. This is required for `ci:forward` to work properly (and other ci command such as `ci:close`).

**Comment by p2kmgcl** [comment]
@jpince @yichenroy thank you for taking care of this. I just added `liferay-continuous-integration` to this repository :)

**Pull request closed without merging**
