### PR TITLE
dropzone-feedback-109717

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @ealonso @veroglez

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@p2kmgcl rebase error on my origin, please resend.

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
https://github.com/ealonso/liferay-portal/pull/2861

**Comment by yichenroy** [comment]
@p2kmgcl please add `liferay-continuous-integration` as a collaborator for your `liferay-portal` repository, it is necessary for the user to update status/labels, instructions can be found [here](https://in.liferay.com/web/global.engineering/wiki/-/wiki/Quality+Assurance+Main/How+To+Set+a+GitHub+Collaborator+To+Your+Repository):

**Pull request closed without merging**
