### PR TITLE
LPS-97017 Honor bootstrap default padding when x1 horizontal padding is selected instead of px-3 to avoid inconsistencies in alignment

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74800. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
