### PR TITLE
LPS-99137 Replace add menu awesome icons

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76627. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76628. [See changes here.](https://github.com/p2kmgcl/liferay-portal/compare/c1ad6bf358c1~1...c1ad6bf358c1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
