### PR TITLE
LPS-105667 - set overflow to visible to account for dropdown menus

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Hey @p2kmgcl, I'm not totally sure who i responsible for this code, but I saw your name in the commit history.

I was looking into https://issues.liferay.com/browse/LPS-105667 and came across an issue where our alignment library doesn't work properly for our case. I actually think the library is accurate in accounting for overflow, but I think our css might be wrong on our end. Can you verify this and see if this causes other issues? I tested it manually, but since I am unfamiliar with the project, I couldn't be sure.

I also opened an issue with the align library in case if might be their issue. https://github.com/yiminghe/dom-align/issues/50

Let me know what you think.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
testing :musical_note: 
(sorry for the delay)

**Comment by p2kmgcl** [comment]
@bryceosterhaus I don't think we can simply remove that CSS, here is the difference:

By setting `overflow-y: auto`, we are preventing the page scroll, because we cant the scrollbar to be placed next to the page content, not at the right of the page: 
overflow-y-auto

However if we change this to `overflow: visible` the scroll returns to the full body, and we lose this behavior:
overflow-visible

If you can think of other way to keep this scrollbar next to the page content it would be perfect, otherwise I think that would cause another issue.

**Comment by bryceosterhaus** [comment]
@p2kmgcl, One other option is to keep the overflow as auto, but add `position: static;` instead on the #wrapper. I went through and tested it and didnt see any issues, but I'm hesitant to make the change. Do you see any issues with that?

**Comment by p2kmgcl** [comment]
@bryceosterhaus I checked that with @marcoscv-work and that should be fine. I'm gonna check if everything works on IE11 (:cry:) and send it to Brian

Thanks!

**Comment by p2kmgcl** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/83379

**Comment by bryceosterhaus** [comment]
Great. And if there is any progress on the dom-align issue, I will remember to go back and update this as well. Thanks!

**Pull request closed without merging**
