### PR TITLE
LPS-92293 jest --updateSnapshot

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-92293

### CODE REVIEW

**Comment by kyle-miho** [comment]
cc: @ealonso @sandrow3

**Comment by p2kmgcl** [comment]
Just started reviewing :)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69718.

**Comment by p2kmgcl** [comment]
@kyle-miho thanks so much :)

**Pull request closed without merging**
