### PR TITLE
LPS-95093 Fix Jsdocs

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Just started reviewing :)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72677. [See changes here.](https://github.com/p2kmgcl/liferay-portal/compare/4f11e05d6fd0~1...4f11e05d6fd0)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72678. [See changes here.](https://github.com/p2kmgcl/liferay-portal/compare/258bcf98dbc6~1...258bcf98dbc6)

**Pull request closed without merging**
