### PR TITLE
LPS-97527 On experience change, render fragmentEntryLinks again to apply segmented configuration values

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
@andresfulla

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
@ruben-pulido

**Comment by p2kmgcl** [comment]
Moreover if you can make the reducer synchronous it would be wonderful, but JSDOCS

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75525. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
@victorg1991 if you create a new Segment (and experience) from page editor. Fragment does not render until you change it's configuration.

**Pull request closed without merging**
