### PR TITLE
fixing-tab-text-in-page-view-109298

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @ealonso @veroglez

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
https://github.com/ealonso/liferay-portal/pull/2857

**Pull request closed without merging**
