### PR TITLE
LPS-95382 Update style

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Just started reviewing :)

**Comment by p2kmgcl** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73448. [See changes here.](https://github.com/p2kmgcl/liferay-portal/compare/dccdf03ef83d~1...dccdf03ef83d)

**Pull request closed without merging**
